version: '3.9'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      - mqtt_net
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:2.0
    ports:
      - "8086:8086"
    networks:
      - database_net
      - grafana_net
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: adminpass
      INFLUXDB_ORG: my-org
      INFLUXDB_BUCKET: my-bucket

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - grafana_net
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: adminpass

  mqtt-adaptor:
    image: mqtt-adaptor
    build:
      context: ..
      dockerfile: Dockerfile
    networks:
      - mqtt_net
      - database_net
    environment:
      - MQTT_BROKER=tcp://mosquitto:1883
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=2uXS_lZCpul4dufOW7Eb5zTspd1D5eu4YZEAGlwZNwI4YdyNNvOIOJcVTaNshupPa3hyOXrix1dM2nne3pKbWg==
      - INFLUXDB_PASSWORD=/run/secrets/influxdb_admin_password
      - INFLUXDB_ORG=SCD
      - INFLUXDB_BUCKET=IoT

networks:
  mqtt_net:
    driver: overlay
  database_net:
    driver: overlay
  grafana_net:
    driver: overlay

volumes:
  influxdb-data:
