version: '3.9'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      - mqtt_net
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:1.8
    networks:
      - database_net
      - grafana_net
    volumes:
      - influxdb1.8-data:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_DATABASE=SCD_IoT
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - grafana_net
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSCD2024
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mqtt-adaptor:
    image: mqtt-adaptor
    build:
      context: ..
      dockerfile: Dockerfile
    networks:
      - mqtt_net
      - database_net
    environment:
      - MQTT_BROKER=tcp://mosquitto:1883
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_DATABASE=SCD_IoT
      - DEBUG_DATA_FLOW=true

networks:
  mqtt_net:
    driver: overlay
  database_net:
    driver: overlay
  grafana_net:
    driver: overlay

volumes:
  influxdb1.8-data:
    driver: local
  grafana-data:
    driver: local
